config/routes.rb
Rails.application.routes.draw do



  

  devise_for :users, :controllers =>{ registrations: "registrations" }
  
  get 'help'=>'static_pages#help'
  get 'contact'=>'static_pages#contact'
  get'welcome'=>'static_pages#welcome'
  get 'expense_income_sheet'=>'static_pages#expense_income_sheet'
  get 'all_income'=>'income#index'
  get 'new_income' => 'income#new'
  post 'new_income' => 'income#new'
  get'income_by_month'=>'income#income_by_month'
  get 'monthly_income/:id'=>'income#monthly'
  
  get 'incomes/:id'=>'income#show'
  patch 'incomes/:id'=>'income#update'
  delete 'incomes/:id'=>'income#destroy'

  get 'new_expenses' => 'transaction#new'
  post'new_expenses'=> 'transaction#new'
  get 'monthly/:id'=>'transaction#monthly_transac'
  get 'transaction_type'=>'transaction#transaction_by_type'
  get 'category/:id'=>'transaction#category_transac'
  get 'all_expense'=>'transaction#index'
  get 'expenses/:id'=>'transaction#show'
  patch 'expenses/:id'=>'transaction#update'
  delete 'expenses/:id'=>'transaction#destroy'

  root 'static_pages#home'  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to:user
    has_many:transactions
end

app/models/income.rb
class Income < ApplicationRecord
    belongs_to :month
    belongs_to:user
    
       validates :amount,presence:{message:"the amount cannot be null"}
       validates :description,presence:{message:"the description cannot be null"}
       validates :month,presence:{message:"please enter a valid month "}
  
       
    def income_by_month
     @total=0
     Income.all.each do|trans|
     
     @total+=trans.amount
     
    end
    return @total
    end 
end

app/models/month.rb
class Month < ApplicationRecord
        belongs_to:user
      has_many :transactions
      has_many :incomes 
   
     
       




   def month_total_expense(month)
      
      if self.id==month.id 
         
         @total_expense=0  
         
          Transaction.all.each do |incomes| 
            
              if incomes.month_id==self.id
                 
                 @total_expense += incomes.amount
                
              end
             
          
           end
            return @total_expense
      end 
   end    
   
 
    def month_total_income(month)
      
      if self.id==month.id 
         
         @total_income=0  
         
          Income.all.each do |incomes| 
            
              if incomes.month_id==self.id
                 
                 @total_income+= incomes.amount
                
              end
             
          
           end
            return @total_income
      end 
    end      
    
      
    def month_rest(month)
       
      @rest=0
      
      if self.id==month.id 
         
        @rest= month_total_income(month)-month_total_expense(month)
        
       return @rest
      else
         return 0
      end 
    end 
    
end 

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to:user
    belongs_to:month
    belongs_to:category
    
       validates :amount,presence:{message:"the amount cannot be null"}
       validates :description,presence:{message:"the description cannot be null"}
       validates :month,presence:{message:"please enter a valid month "}
       validates :category,presence:{message:"please choose a category"}
       
       
       scope :january,->{where(month_id:1)}
       
       
       
 def total_transaction
     @total=0
     Transaction.all.each do|trans|
     
     @total+=trans.amount
     
    end
    return @total
    
 end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :transactions
         has_many :incomes
         has_many :categories
         has_many :months

def username
  
  self.email.split('@')[0].capitalize
  
  
end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
 
 
 def after_sign_in_path_for(resource)
      
    welcome_path
  
 end
  
  
end

app/controllers/income_controller.rb
class IncomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user=current_user
    @income=Income.all 
    @total=0
    
  end

  def new
   
    @month=Month.all
    @income=Income.new 
    @income.amount=params[:amount]
    @income.description=params[:description]
    @income.month_id=params[:month_id]
    @income.user=current_user
    if @income.save
      flash[:success] = "creation success"
       redirect_to"/all_income"
     else
      render 'new'
    end
   
   
 
  end
  
  def monthly
    @total=0
    @month=Month.find(params[:id])
    
  end 
  def show 
    @month=Month.all
    @category=Category.all
    @income=Income.find(params[:id])
    
  end 
  
  def update 
    @income=Income.find(params[:id ])
    @income.amount=params[:amount]
    @income.description=params[:description]
    @income.month_id=params[:month_id]
    @income.user=current_user
    @income.save
    redirect_to"/all_income"
    
   
  end 
  
  def destroy
    
    @income=Income.find(params[:id ])
    @income.destroy
    redirect_to "/all_income"
  end 
  
  def income_by_month
    @transaction=Transaction.all
    @month=Month.all 
  end 
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  
  
   private
   
  
    def after_sign_up_path_for(resource)
      
    welcome_path
  
    end
  
   def after_update_path_for(resource)
      
       welcome_path
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :authenticate_user!,only: [:expense_income_sheet, :welcome]
  
  
  def home
  
  end

  def expense_income_sheet
    
    @income=Income.find(1)
    @expenses=Transaction.find(49)
    @month=Month.all
    @user=current_user
    
    
    
  end
  
  def welcome
    
     @user=current_user
    
  end 

   
  def help
  end

  def contact
  end

  
end 

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  
  
  before_action :authenticate_user!
  before_action :current_user
  
  def index 
 
      
    @transaction=Transaction.all
    @month=Month.all
    @category=Category.all
    @total=0
    @add=0
    
    
  end 
  
  def new
    @user=current_user
    @month=Month.all
    @category=Category.all
    @transaction=Transaction.new 
    @transaction.user=current_user
    @transaction.amount=params[:amount]
    @transaction.description=params[:description]
    @transaction.month_id=params[:month_id]
    @transaction.category_id=params[:category_id]
    
    
    if @transaction.save
    flash[:success] = "creation success"
    redirect_to"/all_expense"
    else
    render 'new'
    end
  end
  
  def show 
    @month=Month.all
    @category=Category.all
    @transaction=Transaction.find(params[:id])
    
  end 
  
  def update 
    @transaction=Transaction.find(params[:id ])
    @transaction.amount=params[:amount]
    @transaction.description=params[:description]
    @transaction.month_id=params[:month_id]
    @transaction.category_id=params[:category_id]
  
    
    if @transaction.save
    flash[:success] = "update success"
    redirect_to"/all_expense"
    else
    render 'show'
    end
    
    
   
  end 
  def destroy
    
    @transaction=Transaction.find(params[:id ])
    @transaction.destroy
    redirect_to "/all_expense"
  end 
  def monthly_transac
    
      @total=0
      @month=Month.find(params[:id])
   
  end 
  
  def transaction_by_type
    @month=Month.all
    @category=Category.all
    
  end 
  
  def category_transac
    @user=current_user
    @total=0
    @category=Category.find(params[:id])
  end 

  private 
  
  def transactions_params
    params.require(:transactions).permit(:amount,:description,:month_id,:category_id)
  end 

  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "easy_bank"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
    

   
   
end

app/views/income/income_by_month.html.erb
<h1>Choose a Month to see the income you made  that month </h1>

  <% @month.each do|month|%>
  
  <P><a href="/monthly_income/<%=month.id%>"><%= month.name %></a></P>
  <%end %>

app/views/income/index.html.erb
<h1>Here are all your income to date  </h1>


 
 
 
 
  <table class=table>
  <tr>
   <th>  ID</th>
    <th>DESCRIPTION</th>
   <th>  AMOUNT </th>
   <th>  MONTH </th>
    <th >    CREATED_AT</th>
    <th>  UPDATE </th>
        <th>  DELETE </th>
  </tr>
  
  <% @user.incomes.each do |income|%>

  
  <tr>
   <td> <%=income.id%> </td>
   
  <td> <%=income.description%> </td>
  
  <td> $<%=income.amount%> </td>
    
  <td>   <%=income.month.name %></td>
  
   <td>  <%=income.created_at%> </td>
   
    <td>  <a href="/incomes/<%=income.id%>">update</a></td>
    
    <td>  <%= form_tag "/incomes/#{income.id}",method:"delete" do  %>
          <input type="submit" value="delete" />
          <%end%>
    </td>
 </tr>
 <%end %> 

 </table>
<% @total=0%>
 
<% @user.incomes.each do |income|%> 

   <% @total=@total+income.amount%> 
   
 <%end %> 
 
 
<P>the total income made is:$<%= @total %> </P> 


 
 

<ul>

 <li><%=link_to "new income? ",new_income_path %></li>
  <li><%=link_to "click to see your monthly income? ",income_by_month_path %></li>
   
 
</ul>

app/views/income/monthly.html.erb
<h1>ALL YOUR INCOME MONTHLY</h1>

<h2><%= @month.name%></h2>


<% @month.incomes.each do |income|%> 
 <tr> <% if current_user.id==income.user_id%>
   <p> amount: <%= income.amount %>,description:<%= income.description%>,month:<%= income.month.name %> 
   <%end%>
 <%end %> 
 
 
 <% @month.incomes.each do|trans| %>
  <tr> <% if current_user.id==trans.user_id%>
   <%if trans.amount%>
   
  <P><%@total=trans.amount + @total %></P>
  
  <%else %>
  
  <%end %>
 <% end %>
<% end %>

 <P>the total amount of this month :<%=@total%></P>

app/views/income/new.html.erb
<h1>create a new Income </h1>

<div class="form-group">
<%= form_tag "/new_income",method:"post" do  %>

 <label for="sname">amount</label>
 <input type="text" name="amount"  placeholder="amout" />
 
 
 <label for="sname">description</label>
 
 <input type="text" name="description" placeholder="description"/>

 <label for="sname">month</label>
   <select name="month_id"
    
   <%= @month.each do |month|%>
  <option value="<%= month.id %>">  <%=month.name%>  </option>
   <%end%>
    
 </select>
 
 

 <input type="submit" value="ajout " />


</div>

<% end %>

app/views/income/show.html.erb
<table class=table>
    
    
    <tr>
        <th>AMOUNT</th>
        <th>DESCRIPTION</th>
        <th>MONTH</th>
      
    </tr>
    
    <tr>
   <td><%=@income.amount %></td>
   <td><%=@income.description%></td>
   <td><%=@income.month.name%></td>


    </tr>


</table>

<H1>UPDATE THIS INCOME </H1>

<div class="form-group">
<%= form_tag "/new_income",method:"post" do  %>

 <label for="sname">amount</label>
 <input type="text" name="amount"  placeholder="amout" />
 
 
 <label for="sname">description</label>
 
 <input type="text" name="description" placeholder="description"/>

 <label for="sname">month</label>
   <select name="month_id"
    
   <%= @month.each do |month|%>
  <option value="<%= month.id %>">  <%=month.name%>  </option>
   <%end%>
    
 </select>
 
 

 <input type="submit" value="ajout " />


</div>


<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    
    <ul>
    

      <li><%= link_to "Contact", contact_path  %></li>
     
     
    </ul>
    
  </nav>
  
</footer>

app/views/layouts/_form_income.html.erb
<div class="form-group">
<%= form_tag "/new_income",method:"post" do  %>

 <label for="sname">amount</label>
 <input type="text" name="amount"  placeholder="amout" />
 
 
 <label for="sname">description</label>
 
 <input type="text" name="description" placeholder="description"/>

 <label for="sname">month</label>
   <select name="month_id"
    
   <%= @month.each do |month|%>
  <option value="<%= month.id %>">  <%=month.name%>  </option>
   <%end%>
    
 </select>
 
 

 <input type="submit" value="ajout " />


</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    
     <% if user_signed_in? %>
      <%= link_to "UBank", welcome_path, id: "logo" %>
       <%else%>
       <%= link_to "UBank", root_path, id: "logo" %>
      <%end%>
    <nav>
      
      
     <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
                   <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |</li>
             <li>  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            
           <%else %>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Log in", new_user_session_path %></li>
   
   
           <%end %>
      
       
       
         
         
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div><%= flash[:success] %></div>
      <%= render 'layouts/header' %>
   
      
      
      <%= yield %>
      
      
      
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/expense_income_sheet.html.erb
<h1>here is a monthly balance of our bank </h1>


  <table class=table>
      
      <tr>
          <th>MONTH</th>
           <th>INCOME</th>
            <th>EXPENSES</th>
             <th>REST</th>
             
      </tr>
      
     
        <% @month.each do|month| %>
      <tr>
         
         
  
          
               <td> <%=month.name%>  </td>
               
                <td>  $<%=month.month_total_income(month)%>  </td>
              
               <td>  $<%=month.month_total_expense(month)%>  </td>
       
                <td> $<%=  month.month_rest(month)  %> </td> 
              
          
         
       
      </tr>
     
      <%end  %>
      
     
      
      
  </table>

  
  <P>total income : $<%= @income. income_by_month%></P>
  <P> total expenses : $<%= @expenses.total_transaction%></P>
   <P>difference : $<%= @income. income_by_month - @expenses.total_transaction%></P>
  
  <P>cv            </P>
  <P>          </P>
   <P>      </P>
  
  <%= line_chart @month.each{ |goal|
  
    {month: goal.name, data: goal.month_total_income(goal)}
} %>
  
  <P>total income : $<%= @income. income_by_month%></P>
  <P> total expenses : $<%= @expenses.total_transaction%></P>
   <P>difference : $<%= @income. income_by_month - @expenses.total_transaction%></P>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="home">
    
    <h1> welcome to Ubank  </h1>
    <h2>This bank was created to help with day to day transactions,it's basically gonna help you to stay on top of your finance </h2>
    <h2>do you want to give it a try?</h2>

</div>

app/views/static_pages/welcome.html.erb
<div class="center jumbotron">
 
<h1>Welcome to your personalise Bank:<%= current_user.username%> </h1>
<h2>choose what kind of transaction would you like to pass </h2>

</div>



<div class="footer-location">
 
 
<ul  class="list-group">
 
 <li class="list-group-item"><%=link_to "ADD A NEW EXPENSE" ,new_expenses_path %></li>
 <li class="list-group-item"><%=link_to "ALL YOUR EXPENSES",all_expense_path %></li>
 <li class="list-group-item"><%=link_to "ADD A NEW INCOME",new_income_path %></li>
  <li class="list-group-item"><%=link_to"ALL YOUR INCOMES",all_income_path %></li>
  
   <li class="list-group-item"><%=link_to "EXPENSES BY TYPE",transaction_type_path %></li>
 <li class="list-group-item"><%=link_to "INCOME BY TYPE",income_by_month_path %></li>
 
  <li class="list-group-item"><%=link_to "BANK OVER-VIEUW",expense_income_sheet_path %></li>
 

 
</ul>

</div>

app/views/transaction/category_transac.html.erb
<h1>this page will show all the transaction by category</h1>

<h1><%= @category.name%></h1>




<table class=table>
  <tr>
   <th>  ID</th>
    <th>DESCRIPTION</th>
   <th>  AMOUNT </th>
   <th>  MONTH </th>
   <th >    CATEGORY</th>
    <th >    CREATED_AT</th>
  </tr>
  
  
  <% @category.transactions.each do |category|%>
 
   


  <tr>
   
    <% if current_user.id==category.user_id%>
    
   <td> <%=category.id%> </td>
  <td> <%=category.description%> </td>
  
  <td> $<%=category.amount%> </td>
    
  <td>   <%=category.month.name %></td>
      
  <td>  <%=category.category.name %> </td>
   
   <td>  <%=category.created_at%> </td>
   <%end %> 
 </tr>
 
<%end %> 
 </table>
 
 
 
 
 
 
 <% @category.transactions.each do|trans| %>
  <% if current_user.id==c=trans.user_id%>
   <%if trans.amount%>
   
  <P><%@total=trans.amount + @total %></P>
  
  <%else %>
  
  <%end %>
 <% end %>
<% end %>

 <P>the total amount of this category is :$<%=@total%></P>
  

app/views/transaction/index.html.erb
<body>
<h1>Here are all the expenses to date </h1>





 <table class=table>
  <thead class="thead-dark">
    <tr>
  

   <th>  ID</th>
    <th>DESCRIPTION</th>
   <th>  AMOUNT </th>
   <th>  MONTH </th>
   <th >    CATEGORY</th>
    <th >    CREATED_AT</th>
     <th>  UPDATE </th>
        <th>  DELETE </th>
   </tr>
 
 </thead>

  <% current_user.transactions.each do|trans| %>
  
 
   
  <tr>
   
   
   <td> <%=trans.id%> </td>
  <td> <%=trans.description%> </td>
  
  <td> $<%=trans.amount%> </td>
    
  <td>   <%=trans.month.name %></td>
      
  <td>  <%=trans.category.name %> </td>
   
   <td>  <%=trans.created_at%> </td>
    <td>  <a href="/expenses/<%=trans.id%>">update</a></td>
    
      <td>  <%= form_tag "/expenses/#{trans.id}",method:"delete" do  %>
          <input type="submit" value="delete" />
          <%end%>
  
   
    </td>
  
 </tr>
  
<%end %> 
 </table>
 

  <% current_user.transactions.each do|trans| %>

   <%if trans.amount%>
   
  <P><%@total=trans.amount + @total %></P>
  
  <%else %>
  
 
  <%end %>
<% end %>


<div=expenses.total>
 
 <P>all expenses total :$<%=@total%></P>
</div>



<ul>
 <li><%=link_to "expense by category ",transaction_type_path %></li>
 <li><%=link_to "new expense? ",new_expenses_path %></li>
 
</ul>


</body>

app/views/transaction/monthly_transac.html.erb
 <h2><%=@month.name%> transactions</h2>
 <table class=table>
  <tr>
   <th>  ID</th>
    <th>DESCRIPTION</th>
   <th>  AMOUNT </th>
   <th>  MONTH </th>
   <th >    CATEGORY</th>
    <th >    CREATED_AT</th>
  </tr>
  
  <% @month.transactions.each do |month|%>
   
  
  <tr> <% if current_user.id==month.user_id%>
   <td> <%=month.id%> </td>
  <td> <%=month.description%> </td>
  
  <td> $<%=month.amount%> </td>
    
  <td>   <%=month.month.name %></td>
      
  <td>  <%=month.category.name %> </td>
   
   <td>  <%=month.created_at%> </td>
   <%end %> 
 </tr>
 <%end %> 

 </table>
 
 
 
 
 
 <% @month.transactions.each do|month| %>
 <% if current_user.id==month.user_id%>
   <%if month.amount%>
   
  <P><%@total=month.amount + @total %></P>
  
  <%else %>
  
  <%end %>
 <% end %>
<% end %>

 <P>the total expenses for this month:$<%=@total%></P>

app/views/transaction/new.html.erb
<h1>Create a new expense </h1>



<%= form_tag "/new_expenses",method:"post" do  %>

<div class="form-group">
     <label for="fname">amount</label>
     <input type="text" name="amount" placeholder="amout"/>
     
     <label for="sname">description</label>
     <input type="text" name="description" placeholder="description"/>

      <label for="sname">month</label>
      <select name="month_id">
    
    
                <%= @month.each do |month|%>
                   <option value="<%= month.id %>">  <%=month.name%>  </option>
                    <%end%>
                 
                </select>
 
       <label for="sname">category</label>
       <select name="category_id">
    
                <%= @category.each do |category|%>
                
               <option value="<%=category.id %>">  <%=category.name%>  </option>
               
                <%end%>
      
                  </select>
 
 
 <input type="submit" value="ajout " />


</form>
</div>

<% end %>

app/views/transaction/show.html.erb
<table class=table>
    
    
    <tr>
        <th>AMOUNT</th>
        <th>DESCRIPTION</th>
        <th>MONTH</th>
        <th>CATEGORY</th>
    </tr>
    
    <tr>
   <td><%=@transaction.amount %></td>
   <td><%=@transaction.description%></td>
   <td><%=@transaction.month.name%></td>
   <td><%=@transaction.category.name%></td>

    </tr>


</table>
<H1>UPDATE THIS EXPENSE </H1>
<%= form_tag "/expenses/",method:"patch" do  %>


<div class="form-group">

     <P>amount:<input type="text" name="amount" /></P>
 
     <P>description:<input type="text" name="description" /></P>


      <P>month: <select name="month_id">
    
    
                <%= @month.each do |month|%>
                   <option value="<%= month.id %>">  <%=month.name%>  </option>
                    <%end%>
                 </P>
                </select>
 
 
       <P>category: <select name="category_id">
    
                <%= @category.each do |category|%>
                
               <option value="<%=category.id %>">  <%=category.name%>  </option>
               
                <%end%>
       </P>
                  </select>
 
 <P>
 <input type="submit" value="ajout " />
</P>

</form>
</div>


<% end %>

app/views/transaction/transaction_by_type.html.erb
<h1> select the month or the category  you would like to see the transaction </h1>

<div class=month_list> 
<h3> MONTH </h3>
<% @month.each do |month| %>

<ul>
  <li>  <a href="/monthly/<%=month.id%>"><%= month.name %></a></li>
 
</ul> 
  <%end%>
</div>
 
 
 <div class=category_list> 
 
<h3> CATEGORY </h3>
 <% @category.each do |category| %>
   <ul>
      <li>  <a href="/category/<%=category.id%>"><%= category.name %></a> </li> 
 
   </ul> 
  <%end%>
  </div>
  
 